### ISSUE TITLE
Property wildcard does not attach to any set

### ISSUE THREAD

**Issue by shehzaman** [robinschiro/MonopolyDeal#95]
Hey @robinschiro a sincere thank you for making this game, especially in times of home quarantine. My family is entertained because of your effort, can't thank you enough!

I have found a few of bugs in release 2.4.1:

1. Property Wildcard does not attach to any set - screenshot below. Ideally we can provide a color it needs to attach to and then play it. 

<img width="1188" alt="Screenshot 2020-03-25 at 4 39 34 PM" src="https://user-images.githubusercontent.com/1736917/77531242-9f11c080-6eb8-11ea-8117-f250442b8aa9.png">

2. Game does not end - same screenshot - 3 sets were made a while back, I think I was at 5 sets now. (just realized this is possibly a duplicate issue)

3. Game crashes when cards run out - I continued playing when the game did not end, and eventually I could see that cards ran out. Is there a reshuffle strategy? It may come up when playing with 5 players.

Each bug above may need its own issue, let me know if you would like it that way.

A few suggestions:

1. Ability to change server port - host multiple games on different ports
2. Make MacOS, Linux or Web application version

I would be more than happy to collaborate with you on making ports to different OS - I am not good with Windows .NET applications, but I would love to try and poke around and see if anything can be done. Any tips from you would be very helpful - I would guess setting up the network is the tricky bit on MacOS and Linux when compared to Windows.

**Comment by robinschiro** [comment]
Wow, you are the first person (that I'm aware of) outside of my friends and family to play this digital version of Monopoly Deal that I created. Thank you very much for the feedback! I am extremely happy that you and your family have been able to enjoy this game during this time.

Here are some notes regarding the issues ones you brought up:

> Property Wildcard does not attach to any set - screenshot below. Ideally we can provide a color it needs to attach to and then play it.

You can attach it to a set, although perhaps the method by which you do so is not very intuitive. You can drag and drop the wildcard onto an incomplete set after you have played it. To separate it from the set, you can right click on it and choose 'Separate Wild Card'.

> Game does not end - same screenshot - 3 sets were made a while back, I think I was at 5 sets now. (just realized this is possibly a duplicate issue)

I'm aware of this one, it is covered by #93 

> Game crashes when cards run out - I continued playing when the game did not end, and eventually I could see that cards ran out. Is there a reshuffle strategy? It may come up when playing with 5 players.

I do have logic to automatically shuffle the discard pile when the deck runs out, I wonder if the discard pile became empty as well after a few reshuffles. I'll try to repro that issue, the game definitely should not crash, but it should end in this scenario. Created #96

Thanks for the suggestions for improvements, I had been planning to make the server port configurable for a while now (just created issue #97) but haven't gotten to it. I have also considered making ports to other OSs, but I believe that would require a full rewrite using a better framework (some web framework like React would be best for this type of game). Main benefit of using a web framework is that we wouldn't have to maintain separate copies of the codebase. Perhaps if we're all quarantined for the next couple of months I will have the time to do this :D

**Comment by shehzaman** [comment]
Fantastic Work! I was digging through your code and you have individually styled each card. That is mighty effort. You're a champian @robinschiro 

> You can attach it to a set, although perhaps the method by which you do so is not very intuitive. You can drag and drop the wildcard onto an incomplete set after you have played it. To separate it from the set, you can right click on it and choose 'Separate Wild Card'.

My bad, I did not notice that cards could be dragged, always right clicked for options. Tested and working perfectly.
 
> I do have logic to automatically shuffle the discard pile when the deck runs out, I wonder if the discard pile became empty as well after a few reshuffles. I'll try to repro that issue, the game definitely should not crash, but it should end in this scenario. Created #96

I will try testing more. This happened two times, could be some underlying issue that I could not catch. Server side I get some warnings, but not sure where those come from.

Another thing I noticed, since client-server communication runs on UDP packets, any drop in connection requires a full restart and abandoning current game. Additionally, if a player makes a move and that UDP packet gets dropped (bad internet), other players do not receive that move, which would mean game has to be restarted. Is this observation correct?

Since each move is quite important to overall state of the game, maybe shifting to WebSocket will help? https://docs.microsoft.com/en-us/dotnet/api/system.web.websockets.aspnetwebsocket?redirectedfrom=MSDN&view=netframework-4.8

WebSocket is available in .NET Framework 4.5+. This way even with spotty connection (like mobile hotspot, pandemic times) we can maintain maintain exact state across all players by ensuring receipt of messages and client-server re-connection through WebSockets. Since messages are small, within a few bytes, this should work really well. 

Let me try looking up how to setup Visual Studio and compile your code, any additional libraries I may need? If I can get this set up, I'll begin contributing with WebSockets.

> I have also considered making ports to other OSs, but I believe that would require a full rewrite using a better framework (some web framework like React would be best for this type of game). Main benefit of using a web framework is that we wouldn't have to maintain separate copies of the codebase. Perhaps if we're all quarantined for the next couple of months I will have the time to do this :D

I agree web application is the right way to go, dug a little deeper, and we have three options that may require lesser effort:

1. Convert existing code base from .NET Framework to .NET Core - https://docs.microsoft.com/en-us/dotnet/core/porting/ - I do not have any experience here, but this can be the one version to maintain and then I can help setup Azure pipelines to make individual OS release on every master commit. I have some experience with pipelines and docker containers - would be happy to help.

2. Using 3rd party binaries for cross compatibility - https://www.mono-project.com/ - skimming through documentation, it seems mono can support iOS and Android too! - https://www.mono-project.com/docs/about-mono/supported-platforms/

3. https://github.com/ASDAlexander77/cs2cpp - convert C# code to c++, I can help with this. Make a c++ back-end with cross-platform c++ GUI elements (like QT) and compile to a static binary, then add separate networking layer to host on any web-server. I can help a lot here, I have some experience with QT, and a lot with c++.

Also let me close this issue, as it is solved.

**Comment by robinschiro** [comment]
> Let me try looking up how to setup Visual Studio and compile your code, any additional libraries I may need? If I can get this set up, I'll begin contributing with WebSockets.

All the DLLs you need are in [this folder](https://github.com/robinschiro/MonopolyDeal/tree/master/Libraries). I think switching to TCP with web sockets is a great idea! When I first started this project, I used the [Lidgren framework](https://github.com/lidgren/lidgren-network-gen3) to handle all of my network communication. This is UDP-based framework, so it may not be possible to continue using it if we switch to TCP. I am okay with that though, since I agree that TCP would be much more reliable (since that is its purpose :D). Since we will likely have to abandon Lidgren, switching to TCP will not be trivial. Perhaps we should try to find a different networking framework that is at least as easy to use.

Regarding porting to other OSs, the easiest way would be to use Xamarin since we should be able to reuse a lot of the existing code. I think that most closely resembles your second suggestion.
